--- 
- name: check directory present or not
  hosts: all
  become: yes
  tasks: 
   - name: check if directory created or not
     stat:
       path: /hoem/ubuntu/f10
     register: b
   - name: display output
     debug:
       var: b
   - name: create file
     file:
       name: /home/ubuntu/f1
       status: touch

     when: b.stat.exists == 'true'
