---
- name: loop baba
  hosts: all
  become: yes
  tasks:
    - name: installing / uninstall or update
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"

      with_items:
        - {a: tree,b: present,c: yes}
        - {a: openjdk-8-jdk,b: present,c: yes }
        - {a: firewalld,b: present,c: yes }

