---
- name: tagging in ansible
  hosts: all
  become: yes
  tasks: 
   - name: install tree
     apt:
       name: tree
       state: latest
     tags: tree.installation

   - name: copy files
     copy:
       src: /etc/passwd
       dest: /tmp


