---
- name: error handling
  hosts: all
  become: yes
  tasks:
   - block:
      - name: install tomcat7 
        apt:
          name: tomcat7
          state: present

     rescue:
      - name: install tomcat8
        apt:
          name: tomcat8
          state: present
     always: 
      - name: restart tomcat8
        service:
          name: tomcat8
          state: restarted
      

